import { analyzeMultiTimeframe, setupQuality, eventRiskGate, liquidityMap, detectSetups, expiryForecasts } from './src/analysis/index.js';
import { loadLiveCandles } from './src/data/live.js';
import { loadNewsRisk } from './src/data/news.js';
import { REALTIME_WS_URL } from './src/config.js';
import { RealtimeFeedClient } from './src/data/realtime.js';

const $=id=>document.getElementById(id);
const state={symbol:'EUR/USD',analysis:null,candles:null,newsRisk:{level:'UNKNOWN',events:[]},setup:null,map:null,ranked:null,forecasts:[],feed:'STARTING',lastTick:null,loading:false,poll:null,ws:null};
const symbolOptions=['EUR/USD','GBP/USD','USD/JPY','AUD/USD','USD/CAD','BTC/USD','ETH/USD','SOL/USD','XRP/USD','BNB/USD','XAU/USD','XAG/USD','WTI/USD','SPX','NDX','DJI','NIFTY'];
const fmt=(v,n=5)=>Number.isFinite(Number(v))?Number(v).toFixed(n):'—';
function setStatus(t){$('statusText').textContent=t}
function initSymbolOptions(){ $('symbol').innerHTML=symbolOptions.map(s=>`<option value="${s}">${s}</option>`).join('');$('symbol').value=state.symbol;updateTitle() }
function updateTitle(){ $('chartTitle').textContent=`${state.symbol} · ${$('tf').value}` }
function customCss(){if($('v4styles'))return;const s=document.createElement('style');s.id='v4styles';s.textContent=`.v4-forecast{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:18px}.v4-box{border:1px solid #183249;border-radius:14px;padding:14px;background:#091725}.v4-box .h{font-size:12px;color:#8ba2b5}.v4-sig{font-weight:900;font-size:24px;margin:5px 0}.v4-call{color:#76d893}.v4-put{color:#e98282}.v4-wait{color:#d5a85c}.v4-meta{font-size:12px;color:#90a7ba}.v4-tick{font-variant-numeric:tabular-nums}.v4-custom{display:flex;gap:8px;align-items:end}.v4-custom input{min-width:140px}.live-badge{font-size:11px;padding:4px 8px;border-radius:999px;background:#102536;border:1px solid #21435d}.@media(max-width:900px){.v4-forecast{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function seedDemo(){const b=state.symbol==='USD/JPY'?157.4:state.symbol.includes('BTC')?104250:state.symbol.includes('ETH')?3820:state.symbol.includes('XAU')?2350:1.084;const mk=(trend)=>{const a=[];let p=b;for(let i=0;i<200;i++){const o=p,c=Math.max(b*.01,p+trend*b+(Math.random()-.5)*b*.0018),h=Math.max(o,c)+Math.random()*b*.001,l=Math.min(o,c)-Math.random()*b*.001;a.push({timestamp:Date.now()-(200-i)*60000,open:o,high:h,low:l,close:c,volume:1000});p=c}return a};state.candles={'1H':mk(.00015),'30M':mk(.00012),'15M':mk(.00009),'5M':mk(.00005),'1M':mk(.00002)};state.feed='DEMO'}
async function load(){const symbol=state.symbol;state.loading=true;setStatus(`LOADING ${symbol}…`);try{const [market,news]=await Promise.allSettled([loadLiveCandles(symbol,200),loadNewsRisk(symbol)]);state.newsRisk=news.status==='fulfilled'&&news.value?news.value:{level:'UNKNOWN',events:[]};if(market.status==='fulfilled'&&market.value){state.candles=market.value;state.feed='LIVE'}else{seedDemo()}state.analysis=analyzeMultiTimeframe(state.candles);render();if(state.feed==='LIVE')connectRealtime()}catch(e){seedDemo();state.analysis=analyzeMultiTimeframe(state.candles);render();setStatus('DATA ERROR · DEMO ONLY');console.error(e)}finally{state.loading=false}}
function connectRealtime(){if(!REALTIME_WS_URL)return;state.ws?.close();try{state.ws=new RealtimeFeedClient({url:REALTIME_WS_URL,symbol:state.symbol,onStatus:s=>{if(s.status==='LIVE')setStatus(`LIVE TICK · ${state.symbol} · ${fmt(state.lastTick?.price,5)}`);else if(s.status==='STALE')setStatus('LIVE FEED STALE · REFRESHING…')},onTick:t=>{state.lastTick=t;applyTick(t);}}).connect()}catch(e){console.warn('Realtime gateway unavailable',e)}}
function applyTick(t){const a=state.candles?.['1M'];if(!a?.length)return;const bucket=Math.floor(t.timestamp/60000)*60000;let c=a[a.length-1];if(Number(c.timestamp)!==bucket){c={timestamp:bucket,open:t.price,high:t.price,low:t.price,close:t.price,volume:t.volume};a.push(c);if(a.length>200)a.shift()}else{c.high=Math.max(c.high,t.price);c.low=Math.min(c.low,t.price);c.close=t.price;c.volume=(c.volume||0)+(t.volume||0)}state.candles['5M']=aggregate(a,5);state.candles['15M']=aggregate(a,15);state.candles['30M']=aggregate(a,30);state.candles['1H']=aggregate(a,60);state.analysis=analyzeMultiTimeframe(state.candles);render()} 
function aggregate(a,mins){const out=[];for(const c of a){const bucket=Math.floor(Number(c.timestamp)/(mins*60000))*(mins*60000);let x=out[out.length-1];if(!x||x.timestamp!==bucket){x={timestamp:bucket,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume};out.push(x)}else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.volume=(x.volume||0)+(c.volume||0)}}return out.slice(-200)}
function renderForecasts(){const host=$('forecastGrid');host.innerHTML=state.forecasts.map(f=>`<div class="v4-box"><div class="h">NEXT ${f.minutes} MIN</div><div class="v4-sig ${f.signal==='CALL'?'v4-call':f.signal==='PUT'?'v4-put':'v4-wait'}">${f.signal}</div><div><strong>${f.confidence}%</strong> · ${f.strength}</div><div class="v4-meta">${f.reasons[0]}</div></div>`).join('')}
function draw(){const c=$('chart'),x=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth,h=300;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.strokeStyle='#183249';for(let y=25;y<h;y+=42){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}const key=({'1m':'1M','5m':'5M','15m':'15M','30m':'30M','1h':'1H'})[$('tf').value];const a=state.candles?.[key];if(!a?.length)return;const v=a.slice(-90),lo=Math.min(...v.map(k=>k.low)),hi=Math.max(...v.map(k=>k.high)),r=Math.max(hi-lo,1e-12),step=(w-24)/v.length,bw=Math.max(3,step*.62),y=z=>14+(hi-z)/r*(h-28);v.forEach((k,i)=>{const px=12+i*step+step/2,up=k.close>=k.open;x.strokeStyle=up?'#75d58a':'#e47777';x.beginPath();x.moveTo(px,y(k.high));x.lineTo(px,y(k.low));x.stroke();x.fillStyle=x.strokeStyle;x.fillRect(px-bw/2,Math.min(y(k.open),y(k.close)),bw,Math.max(1.5,Math.abs(y(k.open)-y(k.close))))});
 if(state.lastTick?.price&&state.feed==='LIVE'&&state.lastTick.price>=lo&&state.lastTick.price<=hi){x.strokeStyle='#76c7ff';x.setLineDash([2,3]);x.beginPath();x.moveTo(0,y(state.lastTick.price));x.lineTo(w,y(state.lastTick.price));x.stroke();x.setLineDash([])} }
function render(){const a=state.analysis;if(!a)return;const f=a.frames?.['5M'];state.setup=setupQuality({analysis:a,newsRisk:state.newsRisk.level});state.map=liquidityMap(state.candles?.['5M']||[],f?.atr||0);state.ranked=detectSetups({candles:state.candles?.['5M'],analysis:a,map:state.map,newsRisk:state.newsRisk.level,sessionLevel:state.setup.session.level});state.forecasts=expiryForecasts({analysis:a,candles:state.candles,newsRisk:state.newsRisk.level,sessionLevel:state.setup.session.level});const decision=state.ranked?.decision||'NO TRADE';const conf=state.ranked?.strongest?.score??state.forecasts[0]?.confidence??50;const riskBlock=eventRiskGate(state.newsRisk).blocked;const final=(riskBlock||decision==='NO TRADE')?'NO TRADE':decision;$('signal').textContent=final;$('confidence').textContent=`${conf}%`;$('signalPill').textContent=final==='CALL'?'CALL · BULLISH':final==='PUT'?'PUT · BEARISH':'NO TRADE · WAIT';$('entry').textContent=final==='NO TRADE'?'—':fmt(state.ranked.strongest.entry);$('stop').textContent=final==='NO TRADE'?'—':fmt(state.ranked.strongest.invalidation);$('target').textContent=final==='NO TRADE'?'—':fmt(state.ranked.strongest.targets?.[0]);$('rr').textContent=final==='NO TRADE'?'—':`1:${state.ranked.strongest.rr.toFixed(1)}`;$('regime').textContent=a.higherTimeframeBias==='BULLISH'?'Bullish':a.higherTimeframeBias==='BEARISH'?'Bearish':'Balanced';$('regimeDetail').textContent=`${state.feed} · MTF · ${state.setup.grade}-grade`;$('why').textContent=final==='NO TRADE'?`No qualified setup. ${state.newsRisk.level==='HIGH'?'High-impact event risk blocks entries.':state.ranked?.strongest?.reasons?.join(' ')||'Wait for structure and confirmation.'}`:`${final} selected from MTF structure, liquidity, momentum and risk filters.`;$('strongest').textContent=final==='NO TRADE'?'NO TRADE':`${final} · ${state.ranked.strongest.grade}-GRADE`;$('strongestText').textContent=state.ranked?.strongest?.reasons?.join(' ')||'The engine is waiting for a confirmed setup.';const checks=[['HTF structure',a.higherTimeframeBias==='CONFLICT'||a.higherTimeframeBias==='RANGE'?'WAIT':'PASS'],['Liquidity sweep',state.ranked?.strongest?.reasons?.some(r=>r.includes('sweep'))?'PASS':'WAIT'],['Displacement',state.ranked?.strongest?.reasons?.some(r=>r.includes('Displacement'))?'PASS':'WAIT'],['BOS / CHOCH',state.map?.structure?.bos||state.map?.structure?.choch?'PASS':'WAIT'],['Risk / reward',state.ranked?.strongest?.rr>=1.5?'PASS':'BLOCK'],['News',state.newsRisk.level==='HIGH'?'BLOCK':state.newsRisk.level]);$('checks').innerHTML=checks.map(([n,s])=>`<div class="check"><span>${n}</span><b class="${s==='PASS'?'ok':'warn'}">${s}</b></div>`).join('');$('confidence').className='score v4-tick';setStatus(state.feed==='LIVE'?`LIVE MARKET · ${state.symbol}${state.lastTick?` · ${fmt(state.lastTick.price)}`:''}`:`DEMO DATA · ${state.symbol}`);renderForecasts();draw()}
function watch(){const list=['EUR/USD','GBP/USD','USD/JPY','BTC/USD','ETH/USD','XAU/USD','NIFTY'];$('watchlist').innerHTML=list.map(n=>`<button class="watch" type="button" data-symbol="${n}"><strong>${n}</strong><small>Live AI scan</small><b>ANALYZE</b></button>`).join('');document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{state.symbol=b.dataset.symbol;initSymbolOptions();load()})}
function refresh(){if(state.loading)return;load()}
customCss();initSymbolOptions();watch();$('assetClass').onchange=()=>{};$('symbol').onchange=()=>{state.symbol=$('symbol').value;updateTitle();load()};$('tf').onchange=()=>{updateTitle();draw()};$('mode').onchange=render;$('scanBtn').onclick=()=>{if(!state.loading)load()};$('refreshBtn').onclick=()=>{if(!state.loading)load()};
const expiryHost=document.createElement('section');expiryHost.className='card';expiryHost.innerHTML='<div class="section-head"><div><p class="eyebrow">AI EXPIRY FORECAST</p><h2>CALL / PUT / NO TRADE by horizon</h2></div><span class="live-badge">5 · 10 · 15 · 30 · 60 MIN</span></div><div id="forecastGrid" class="v4-forecast"></div>';document.querySelector('main').insertBefore(expiryHost,document.querySelector('.grid'));
load();clearInterval(state.poll);state.poll=setInterval(load,15000);
