import http from 'node:http';
import { WebSocketServer, WebSocket } from 'ws';
import { serveCandles } from './candles-proxy.js';
const PORT=Number(process.env.PORT||8787),API_KEY=process.env.TWELVE_DATA_API_KEY||'',PROVIDER_WS_URL=process.env.TWELVE_DATA_WS_URL||'wss://ws.twelvedata.com/v1/quotes/price';
const normalize=v=>String(v||'').trim().toUpperCase().slice(0,40),providerUrl=()=>{const u=new URL(PROVIDER_WS_URL);u.searchParams.set('apikey',API_KEY);return u.toString()};
function tickOf(m){if(!m||m.event!=='price')return null;const symbol=normalize(m.symbol),price=Number(m.price),raw=Number(m.timestamp);if(!symbol||!Number.isFinite(price)||price<=0)return null;return{type:'tick',symbol,price,timestamp:Number.isFinite(raw)?(raw<1e12?raw*1000:raw):Date.now(),volume:Number(m.day_volume??m.volume??0)||0,source:'twelve-data'}}
class Provider{constructor(b){this.b=b;this.ws=null;this.subs=new Set;this.timer=null;this.reconnect=null;this.closed=false;this.connecting=false}add(s){s=normalize(s);if(!s)return;const empty=!this.subs.size;this.subs.add(s);if(empty)this.connect();else if(this.ws?.readyState===WebSocket.OPEN)this.subscribe()}remove(s){this.subs.delete(normalize(s));if(!this.subs.size)this.disconnect();else if(this.ws?.readyState===WebSocket.OPEN)this.subscribe()}connect(){if(this.closed||!API_KEY||!this.subs.size||this.connecting)return;this.connecting=true;let ws;try{ws=new WebSocket(providerUrl())}catch{this.connecting=false;return this.retryConnect()}this.ws=ws;ws.on('open',()=>{this.connecting=false;this.subscribe();clearInterval(this.timer);this.timer=setInterval(()=>this.ws?.readyState===WebSocket.OPEN&&this.ws.send(JSON.stringify({action:'heartbeat'})),10000)});ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}const t=tickOf(m);if(t&&this.subs.has(t.symbol))this.b(t)});ws.on('error',()=>{});ws.on('close',()=>{this.connecting=false;clearInterval(this.timer);this.timer=null;if(this.ws===ws)this.ws=null;if(!this.closed&&this.subs.size)this.retryConnect()})}subscribe(){if(this.ws?.readyState===WebSocket.OPEN&&this.subs.size)this.ws.send(JSON.stringify({action:'subscribe',params:{symbols:[...this.subs].join(',')}}))}retryConnect(){if(this.reconnect||this.closed||!this.subs.size)return;this.reconnect=setTimeout(()=>{this.reconnect=null;this.connect()},2000)}disconnect(){clearTimeout(this.reconnect);this.reconnect=null;clearInterval(this.timer);this.timer=null;this.ws?.close();this.ws=null}close(){this.closed=true;this.disconnect()}}
const server=http.createServer(async(req,res)=>{const origin=process.env.ALLOWED_ORIGIN||'*';res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store');const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(u.pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({status:'ok',service:'market-ai-trader-v4-realtime',providerConfigured:Boolean(API_KEY),candlesProxy:true,websocket:true}))}if(u.pathname==='/candles'&&req.method==='GET')return serveCandles(u,res,API_KEY);res.writeHead(404,{'content-type':'application/json'});res.end(JSON.stringify({error:'Not found'}))});
const wss=new WebSocketServer({server,path:'/stream'}),clients=new Map(),provider=new Provider(t=>{const p=JSON.stringify(t);for(const[c,s]of clients)if(c.readyState===WebSocket.OPEN&&s.has(t.symbol))c.send(p)});
wss.on('connection',c=>{const s=new Set;clients.set(c,s);c.send(JSON.stringify({type:'gateway',status:API_KEY?'READY':'UNCONFIGURED',timestamp:Date.now()}));c.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.action==='ping')return c.send(JSON.stringify({type:'heartbeat',timestamp:Date.now()}));if(m.action==='subscribe'&&m.symbol){const x=normalize(m.symbol);s.add(x);provider.add(x);return c.send(JSON.stringify({type:'subscription',symbol:x,status:'pending'}))}if(m.action==='unsubscribe'&&m.symbol){const x=normalize(m.symbol);s.delete(x);if(![...clients.values()].some(v=>v.has(x)))provider.remove(x)}});c.on('close',()=>{clients.delete(c);for(const x of s)if(![...clients.values()].some(v=>v.has(x)))provider.remove(x)})});
process.on('SIGTERM',()=>{provider.close();wss.close();server.close(()=>process.exit(0))});process.on('SIGINT',()=>{provider.close();wss.close();server.close(()=>process.exit(0))});server.listen(PORT,()=>console.log(`V4 realtime gateway listening on ${PORT}`));