import http from 'node:http';
import { WebSocketServer, WebSocket } from 'ws';
const PORT=Number(process.env.PORT||8787),API_KEY=process.env.TWELVE_DATA_API_KEY||'',PROVIDER_WS_URL=process.env.TWELVE_DATA_WS_URL||'wss://ws.twelvedata.com/v1/quotes/price';
const normalize=v=>String(v||'').trim().toUpperCase().slice(0,40);
function providerUrl(){const u=new URL(PROVIDER_WS_URL);u.searchParams.set('apikey',API_KEY);return u.toString()}
function normalizeProviderMessage(m){if(!m||m.event!=='price')return null;const symbol=normalize(m.symbol),price=Number(m.price),raw=Number(m.timestamp);if(!symbol||!Number.isFinite(price)||price<=0)return null;return{type:'tick',symbol,price,timestamp:(raw<1e12?raw*1000:raw)||Date.now(),volume:Number(m.day_volume??m.volume??0)||0,source:'twelve-data'}}
class Provider{constructor(broadcast){this.broadcast=broadcast;this.ws=null;this.subs=new Set();this.timer=null;this.reconnect=null;this.closed=false;this.connecting=false}add(symbol){const s=normalize(symbol);if(!s)return;const empty=!this.subs.size;this.subs.add(s);if(empty)this.connect();else if(this.ws?.readyState===WebSocket.OPEN)this.subscribe()}remove(symbol){this.subs.delete(normalize(symbol));if(!this.subs.size)this.disconnect();else if(this.ws?.readyState===WebSocket.OPEN)this.subscribe()}connect(){if(this.closed||!API_KEY||!this.subs.size||this.connecting)return;this.connecting=true;let ws;try{ws=new WebSocket(providerUrl())}catch{this.connecting=false;return this.retryConnect()}this.ws=ws;ws.on('open',()=>{this.connecting=false;this.subscribe();clearInterval(this.timer);this.timer=setInterval(()=>{if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify({action:'heartbeat'}))},10000)});ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}const t=normalizeProviderMessage(m);if(t&&this.subs.has(t.symbol))this.broadcast(t)});ws.on('error',()=>{});ws.on('close',()=>{this.connecting=false;clearInterval(this.timer);this.timer=null;if(this.ws===ws)this.ws=null;if(!this.closed&&this.subs.size)this.retryConnect()})}subscribe(){if(this.ws?.readyState===WebSocket.OPEN&&this.subs.size)this.ws.send(JSON.stringify({action:'subscribe',params:{symbols:[...this.subs].join(',')}}))}retryConnect(){if(this.reconnect||this.closed||!this.subs.size)return;this.reconnect=setTimeout(()=>{this.reconnect=null;this.connect()},2000)}disconnect(){clearTimeout(this.reconnect);this.reconnect=null;clearInterval(this.timer);this.timer=null;this.ws?.close();this.ws=null}close(){this.closed=true;this.disconnect()}}
const server=http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin',process.env.ALLOWED_ORIGIN||'*');res.setHeader('Cache-Control','no-store');if(req.url==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({status:'ok',service:'market-ai-trader-v4-realtime',providerConfigured:Boolean(API_KEY)}))}res.writeHead(404);res.end()});
const wss=new WebSocketServer({server,path:'/stream'}),clients=new Map();
const provider=new Provider(tick=>{const payload=JSON.stringify(tick);for(const [client,subs] of clients)if(client.readyState===WebSocket.OPEN&&subs.has(tick.symbol))client.send(payload)});
wss.on('connection',client=>{const subs=new Set();clients.set(client,subs);client.send(JSON.stringify({type:'gateway',status:API_KEY?'READY':'UNCONFIGURED',timestamp:Date.now()}));client.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.action==='ping')return client.send(JSON.stringify({type:'heartbeat',timestamp:Date.now()}));if(m.action==='subscribe'&&m.symbol){const s=normalize(m.symbol);subs.add(s);provider.add(s);return client.send(JSON.stringify({type:'subscription',symbol:s,status:'pending'}))}if(m.action==='unsubscribe'&&m.symbol){const s=normalize(m.symbol);subs.delete(s);if(![...clients.values()].some(set=>set.has(s)))provider.remove(s)}});client.on('close',()=>{clients.delete(client);for(const s of subs)if(![...clients.values()].some(set=>set.has(s)))provider.remove(s)})});
process.on('SIGTERM',()=>{provider.close();wss.close();server.close(()=>process.exit(0))});process.on('SIGINT',()=>{provider.close();wss.close();server.close(()=>process.exit(0))});
server.listen(PORT,()=>console.log(`V4 realtime gateway listening on ${PORT}`));
